### ISSUE TITLE
Add fullscreen mode

### ISSUE THREAD

**Issue by megalon** [megalon/BeatSaber-UnofficialTrackEditor#19]
Even just scaling to the size of the window might be OK.

Issues:

This might require scaling the entire UI

**Comment by Expicot** [comment]
Yes, please increase window's size, (or better adjust to desktop size * 0.8), that way those who have large screen have more room for editing ;).

**Comment by megalon** [comment]
It looks like Processing is VERY strict about screen resizing / fullscreen.
It doesn't seem to allow resizing at all. You have to set the value at startup
https://processing.org/reference/fullScreen_.html

**Comment by Expicot** [comment]
Ok, but can you get the screensize and set it up at 80% (by example) ?

https://processing.org/reference/size_.html
http://py.processing.org/reference/displayWidth.html

**Comment by megalon** [comment]
Sorry for the late reply.
Yes that is possible to hardcode in the ability to fullscreen, but there doesn't appear to be an option to disable it without rebuilding the project. I could release a separate build with fullscreen enabled, however currently it wouldn't scale the size of the grid, and you would end up with something like this:

https://i.imgur.com/SVWzPYM.png

When I work on zooming I will spend more time making the grid scale correctly, then I will post here about it again
